### PR TITLE
(master) This creates a PHP74 package and switches the edge profile to use it

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @totten @monishdeb @joeMurray

### CODE REVIEW

**Comment by JoeMurray** [comment]
Can there be two edge packages for PHP at the same time? I think PHP73 should still be edge until we've crushed all of its bugs. Maybe we could make merging this PR dependent on PHP73 being ready to be max stable.

**Comment by totten** [comment]
Rebased and updated to php 7.4.2.

I did a trial run locally. The `php` binaries built without error. Then I tried a `civibuild create d8-master`, which failed. The failure is reproducible with just this command:

```
[bknix-edge:/tmp/q] mkdir -p /tmp/delme && drush8 -y dl drupal-8 --destination=/tmp/delme --drupal-project-rename -v
Include /Users/totten/bknix/civicrm-buildkit/extern/drush-lib                                                                                                                   [notice]
Undefined index: description command.inc:1296                                                                                                                                   [notice]
Undefined index: description command.inc:1296                                                                                                                                   [notice]
Undefined index: description command.inc:1296                                                                                                                                   [notice]
Undefined index: description command.inc:1296                                                                                                                                   [notice]
Undefined index: description command.inc:1296                                                                                                                                   [notice]
Undefined index: description command.inc:1296                                                                                                                                   [notice]
Loading version_control engine.                                                                                                                                                 [notice]
Loading package_handler engine.                                                                                                                                                 [notice]
Executing: wget --version
Loading release_info engine.                                                                                                                                                    [notice]
Downloading release history from https://updates.drupal.org/release-history/drupal/8.x                                                                                          [notice]
Executing: wget --version
Executing: wget -q --timeout=30 -O /private/tmp/download_fileJD3SqW https://updates.drupal.org/release-history/drupal/8.x
Downloading project drupal ...                                                                                                                                                  [notice]
/Users/totten/bknix/build/.civibuild/drush/cache/download/https---ftp.drupal.org-files-projects-drupal-8.8.3.tar.gz retrieved from cache.                                       [notice]
Downloading drupal-8.8.3.tar.gz was successful.                                                                                                                                 [notice]
Md5 checksum of drupal-8.8.3.tar.gz verified.                                                                                                                                   [notice]
Unable to extract /tmp/drush_tmp_1583611449_5e63fe39c29a8/drupal-8.8.3.tar.gz. Unknown archive format.                                                                       [error]
Error downloading drupal                                                                                                                                                        [notice]
Command dispatch complete                                                                                                                                                       [notice]
```

The same failure also occurs in php 7.4.1 -- and with Drupal 7.x.

Unassessed theories:
* (a) The newer build of php is missing some required extension or dataset, perhaps related to mime?
* (b) The drush8 in buildkit has compatibility issues with php74?

**Comment by seamuslee001** [comment]
@totten this suggets there maybe a thing with php7.4 https://drupal.stackexchange.com/questions/291489/drush-up-fails-with-unknown-archive-format and  this might provide an idea around things https://www.drupal.org/project/drush/issues/1721334

**Comment by seamuslee001** [comment]
see also https://github.com/drush-ops/drush/pull/4246

**Comment by seamuslee001** [comment]
@totten now that we have a newer drush in the buildkit I would suggest we should have another crack at this

**Comment by seamuslee001** [comment]
@totten have created a master loco version of this PR here https://github.com/totten/bknix/pull/18

**Comment by totten** [comment]
Since nixpkgs 20.03 is stable now, I updated the relevant pin, and it's now using PHP 7.4.6.

`civibuild` and `civi-test-run` seem to execute well enough to do the test suite. They do give several warnings/errors, but that's expected for `edge`. :+1:

**Pull request merged**
